# Generated by Django 5.1.7 on 2025-08-05 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='assigned_salesperson',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'salesperson'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='users.userprofile'),
        ),
    ]
